### PR TITLE
Explicitly set locale for some test files

### PR DESCRIPTION
**Pull request by MichaelChirico**
I was seeing naming mismatch errors without setting locale to C here.

### CODE REVIEW

**Comment by SebKrantz** [comment]
Thanks @MichaelChirico! Wondering what brings me the honor of you making these edits to collapse's testing facilities?

Also wondered, did CRAN force you to do something about 

```
Result: NOTE
  File ‘data.table/libs/data_table.so’:
    Found non-API calls to R: ‘LEVELS’, ‘NAMED’, ‘SETLENGTH’,
      ‘SET_GROWABLE_BIT’, ‘SET_S4_OBJECT’, ‘SET_TRUELENGTH’,
      ‘UNSET_S4_OBJECT’
```
? I have some of the same notes now.

**Comment by MichaelChirico** [comment]
> Wondering what brings me the honor of you making these edits to collapse's testing facilities?

Finally got around to importing {collapse} as a third-party package internally. We have a "unique" testing environment different from CRAN which can dredge up these sorts of edge cases.

> Also wondered, did CRAN force you to do something about

We have not submitted to CRAN yet, not sure what will be enforced. Follow along at https://github.com/Rdatatable/data.table/issues/6180 :)

**Comment by SebKrantz** [comment]
Ok, thanks! And cool that *collapse* can now be used at Google :)

**Comment by SebKrantz** [comment]
Probably not the way you'll go about it @MichaelChirico, but for the radixsort I implemented a custom TRUELENGTH/SET_TRUELENGTH, which avoids an ALTREP check that made the function noticeably more expensive: https://github.com/SebKrantz/collapse/blob/master/src/base_radixsort.h.

**Comment by MichaelChirico** [comment]
Thanks for sharing! I'd still like to strive to use the public API if possible, let's see how it goes :)

**Comment by SebKrantz** [comment]
@MichaelChirico further to this, I've now done things the dirty way again. CRAN was not responding anymore to my submissions, which I guess is now the way they start cracking down on all non-API compliant smaller packages (not helpful). Just sharing in case it is useful (I can see that the ALTREP solution of aitap is cool but would of course overhaul a large part of your architecture, don't allow `chmatch()` to continue working the smart way you are doing it now etc.). Turns out `(SET_)TRUELENGTH` is rather easy: 

```c
#define STDVEC_TRUELENGTH(x) (((VECSEXP) (x))->vecsxp.truelength)
#define SET_STDVEC_TRUELENGTH(x, v) (STDVEC_TRUELENGTH(x)=(v))
// No method to set ALTREP_TRUELENGTH (gives error)
#define SET_TRULEN(x, v) (STDVEC_TRUELENGTH(x)=(v))
// ALTREP_TRUELENGTH is 0: https://github.com/wch/r-source/blob/48f06c1071fea6a6e7e365ad3d745217268e2175/src/main/altrep.c#L345
#define TRULEN(x) (ALTREP(x) ? 0 : STDVEC_TRUELENGTH(x))
```
`SETLENGTH` on the other hand is complicated (see [here](https://github.com/SebKrantz/collapse/blob/4e368448d262d08228f1cc4b31575a85bad22196/src/data.table.h#L26C33-L26C85)). Better get rid of that one if you can. Anyway, just sharing in case you are also getting problems. If the plan is still to do everything in `ALTREP` I will follow along...

**Pull request merged**
